### ISSUE TITLE
pipeline中使用

### ISSUE THREAD

**Issue by Hargeek** [liuweiGL/ding-talk-jenkins#1]
请问这个插件在pipeline中如何使用呢

**Comment by liuweiGL** [comment]
> 请问这个插件在pipeline中如何使用呢

目前官方仓库已经有一个类似的插件导致无法发布，正在走插件的接管流程。插件发布之后根据需求会进行功能添加。

**Comment by ilanni2460** [comment]
没有仔细看，直接升级了插件导致，原来使用pipeline方式的deploy全部报错，请问新版本如何在pipeline中使用？

**Comment by ilanni2460** [comment]
目前暂时回退到原来插件版本，1.9版本

**Comment by liuweiGL** [comment]
> 目前暂时回退到原来插件版本，1.9版本

新版的跟之前的完全不同：

1. 插件配置
2. 钉钉消息类型与消息体
3. 插件通知不区分项目类型，也就是说不管是 FreeStyle Project、Pipeline，插件都是通过监听 Jenkins 提供的事件进行消息发送。
---
插件目前还没有实现在 Jenkinsfile 脚本中使用，后续可能会添加支持。

**Comment by liuweiGL** [comment]
> 目前暂时回退到原来插件版本，1.9版本

另外该插件相关问题应该在 https://github.com/jenkinsci/dingding-notifications-plugin 仓库中进行提问，这个仓库会删除掉的。
